server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: http://localhost:9092
    consumer:
      group-id: message-group-id
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka-topic: messages-topic


